spring:
  data:
    mongodb:
      username: ramon
      password: ramon
      host: localhost
      port: 27017
      database: customerdb
      authentication-database: admin
      auto-index-creation: true
server:
  port: 9090