spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ramon
    password: ramon
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
      use_sql_comments: true
      type:
        org.hibernate.type.descriptor.sql.SqlTypeDescriptor: TRACE
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org.flywaydb.core: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


server:
  port: 9091