CREATE TABLE IF NOT EXISTS category (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('CATEGORY_SEQ'),
  description VARCHAR(255),
  name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS product (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('PRODUCT_SEQ'),
  description VARCHAR(255),
  name VARCHAR(255),
  available_quantity BIGINT NOT NULL,
  price NUMERIC(38, 2),
  category_id BIGINT,
  CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE SEQUENCE IF NOT EXISTS CATEGORY_SEQ INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS PRODUCT_SEQ INCREMENT BY 1;

